-- MySQL Script generated by MySQL Workbench
-- Thu Sep 28 09:07:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Books
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Books` ;

-- -----------------------------------------------------
-- Schema Books
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Books` DEFAULT CHARACTER SET utf8 ;
USE `Books` ;

-- -----------------------------------------------------
-- Table `Books`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Books`.`Author` ;

CREATE TABLE IF NOT EXISTS `Books`.`Author` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Author_name` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Books`.`books` ;

CREATE TABLE IF NOT EXISTS `Books`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL,
  `Author_id` INT NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  `Author_id` INT NOT NULL,
  `Author_id1` INT NOT NULL,
  PRIMARY KEY (`id`, `Author_id`),
  INDEX `fk_books_Author1_idx` (`Author_id1` ASC) VISIBLE,
  CONSTRAINT `fk_books_Author1`
    FOREIGN KEY (`Author_id1`)
    REFERENCES `Books`.`Author` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Books`.`Users` ;

CREATE TABLE IF NOT EXISTS `Books`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(45) NULL,
  `Last_name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `created_at` DATETIME NULL DEFAULT NOW(),
  `updated_at` DATETIME NULL DEFAULT NOW() ON UPDATE NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Books`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Books`.`favorites` ;

CREATE TABLE IF NOT EXISTS `Books`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `books_id` INT NOT NULL,
  `books_Author_id1` INT NOT NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_favorites_books1_idx` (`books_id` ASC, `books_Author_id1` ASC) VISIBLE,
  INDEX `fk_favorites_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_favorites_books1`
    FOREIGN KEY (`books_id` , `books_Author_id1`)
    REFERENCES `Books`.`books` (`id` , `Author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favorites_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `Books`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
